@startuml
'https://plantuml.com/class-diagram

chats  --  users_chats
chats -- messages
chats --- lastRead

users_chats -- users

messages -- users
messages -- lastRead

users - lastRead
users -- emails

class chats{
    id_chat int {PK}
    title varchar
    id_messages {FK}
}

class users_chats{
    id_user {PK FK}
    id_chat {PK FK}
}

class messages {
    id_chat {FK}
    id_messages {PK}
    id_user {FK}
    message varchar
}

class lastRead{
    id_chat {PK FK}
    id_messages {PK FK}
    id_user {PK FK}
}

class users {
    id_user int {PK}
    username varchar
    name varchar
    tlf varchar
}

class emails {
    email varchar {PK}
    id_user {PK FK}
}

@enduml